name: 0.1.$(Rev:r)
trigger:
  branches:
    include:
    - main
  paths:
    include:
    - Infrastructure/dapr/*
    
variables:
  vmImageName: 'ubuntu-latest'
  azureServiceConnection: 'Demo Account'
  location: 'eastus'
  aksResourceGroupName: 'rutzsco-aks-001'
  aksClusterName: 'aks-rutzsco-aks-001'
  componentPath: 'Infrastructure/dapr'
pool:
  vmImage: $(vmImageName)

steps:

- task: AzureCLI@2
  displayName: Deploy Dapr Components
  inputs:
    azureSubscription: $(azureServiceConnection)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az aks get-credentials -n $(aksClusterName) -g $(aksResourceGroupName)
      kubectl config set-context --current --namespace=dapr-traffic-control
      kubectl create secret generic dapr-traffic-control-sb --from-literal=servicebusconnectionstring='$(SERVICE_BUS_CONNECTION_STRING)'
      kubectl create secret generic dapr-traffic-control-redis --from-literal=redisPassword='$(REDIS_PASSWORD)'
      kubectl create secret generic dapr-traffic-control-iothub --from-literal=iothubconnectionstring='$(IOT_HUB_CONNECTION_STRING)'
      kubectl create secret generic dapr-traffic-control-iothub-sa --from-literal=iothubstorageaccountkey='$(IOT_HUB_STORAGE_ACCOUNT_KEY)'
      kubectl apply -f $(componentPath)/dapr-component-secrets.yml
      kubectl apply -f $(componentPath)/k8-secret-rbac.yml
      kubectl apply -f $(componentPath)/dapr-component-binding-http-mail.yml
      kubectl apply -f $(componentPath)/dapr-component-pubsub-servicebus.yml
      kubectl apply -f $(componentPath)/dapr-component-pubsub-subscription.yml
      kubectl apply -f $(componentPath)/dapr-component-state-redis.yml